//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace steam_idle_gui.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("steam_idle_gui.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting Auto Mode.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  on blacklist, skipping game.
        /// </summary>
        internal static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a blacklist.txt file not found.
        /// </summary>
        internal static string BlacklistNotFound {
            get {
                return ResourceManager.GetString("BlacklistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checking to see if {0} has remaining card drops.
        /// </summary>
        internal static string CheckingDrops {
            get {
                return ResourceManager.GetString("CheckingDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing game .
        /// </summary>
        internal static string ClosingGame {
            get {
                return ResourceManager.GetString("ClosingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Idle needs to idle {0} games.
        /// </summary>
        internal static string CountGamesAuto {
            get {
                return ResourceManager.GetString("CountGamesAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Idle needs to idle .
        /// </summary>
        internal static string CountGamesStart {
            get {
                return ResourceManager.GetString("CountGamesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error checking if drops are done, number of tries remaining: .
        /// </summary>
        internal static string FailError {
            get {
                return ResourceManager.GetString("FailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finding games that have card drops remaining.
        /// </summary>
        internal static string Finding {
            get {
                return ResourceManager.GetString("Finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  games found.
        /// </summary>
        internal static string GamesFound {
            get {
                return ResourceManager.GetString("GamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;re Now In-Game.
        /// </summary>
        internal static string InGame {
            get {
                return ResourceManager.GetString("InGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No card drops remaining.
        /// </summary>
        internal static string NoCard {
            get {
                return ResourceManager.GetString("NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Still unable to find drop info.
        /// </summary>
        internal static string NoDrops {
            get {
                return ResourceManager.GetString("NoDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No game selected.
        /// </summary>
        internal static string NoGameSelect {
            get {
                return ResourceManager.GetString("NoGameSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No sessionid set.
        /// </summary>
        internal static string Nosessionid {
            get {
                return ResourceManager.GetString("Nosessionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No steamLogin set.
        /// </summary>
        internal static string NosteamLogin {
            get {
                return ResourceManager.GetString("NosteamLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not In-Game.
        /// </summary>
        internal static string NotInGame {
            get {
                return ResourceManager.GetString("NotInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has {1} card drops remaining.
        /// </summary>
        internal static string RemainingDrops {
            get {
                return ResourceManager.GetString("RemainingDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.txt file not found.
        /// </summary>
        internal static string SettingsNotFound {
            get {
                return ResourceManager.GetString("SettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleeping for {0} minutes.
        /// </summary>
        internal static string SleepingFor {
            get {
                return ResourceManager.GetString("SleepingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting game {0} to idle cards.
        /// </summary>
        internal static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No steamLogin set.
        /// </summary>
        internal static string steamLoginError {
            get {
                return ResourceManager.GetString("steamLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully completed idling cards for .
        /// </summary>
        internal static string SuccessGame {
            get {
                return ResourceManager.GetString("SuccessGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspending operation for .
        /// </summary>
        internal static string SuspendingGame {
            get {
                return ResourceManager.GetString("SuspendingGame", resourceCulture);
            }
        }
    }
}
